### ISSUE TITLE
Issue with two Yamaha AVRs

### ISSUE THREAD

**Issue by alexargo** [NorthernMan54/homebridge-yamaha-zone-tv#9]
I have two Yamaha TSR-7850s(Hey... they were on sale at Costco.....) and am getting the following error when trying to boot up home bridge:

This puts things in a bad state ends up crashing home bridge 

```/15/2019, 11:21:50 PM] Homebridge is running on port 51826.
[8/15/2019, 11:21:50 PM] [yamaha-zone-tv] Possible Yamaha device discovered Diskstation [ 'fe80::211:32ff:fe33:1601', '192.168.1.47' ]
[8/15/2019, 11:21:50 PM] [yamaha-zone-tv] Possible Yamaha device discovered Basement [ '192.168.1.110', 'fe80::4e1b:86ff:fe89:68aa' ]
[8/15/2019, 11:21:50 PM] [yamaha-zone-tv] Possible Yamaha device discovered Patio [ '192.168.1.74', 'fe80::4e1b:86ff:fea6:3d6a' ]
[8/15/2019, 11:21:51 PM] [yamaha-zone-tv] Found Yamaha TSR-7850 - 03D38A63, "Patio"
[8/15/2019, 11:21:51 PM] [yamaha-zone-tv] Possible Yamaha device discovered EPSON XP-820 Series [ '192.168.1.54', 'fe80::66eb:8cff:fe13:ac1f' ]
[8/15/2019, 11:21:51 PM] [yamaha-zone-tv] Found Yamaha TSR-7850 - 06402303, "Basement"
[8/15/2019, 11:21:51 PM] [yamaha-zone-tv] Adding TV Control for Main
[8/15/2019, 11:21:51 PM] [yamaha-zone-tv] Adding TV Control for Zone2
Unhandled rejection Error: Cannot add a Service with the same UUID '000000D9-0000-1000-8000-0026BB765291' and subtype '15eb8e46-3ee2-4b1e-922a-366be0895315' as another Service in this Accessory.
    at PlatformAccessory.addService (/usr/local/lib/node_modules/homebridge/lib/platformAccessory.js:55:15)
    at YamahaZone.<anonymous> (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/index.js:547:24)
    at Array.forEach (<anonymous>)
    at YamahaZone.getServices (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/index.js:519:12)
    at YamahaAVRPlatform.<anonymous> (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/index.js:198:37)
    at tryCatcher (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:699:18)
    at Promise._fulfill (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:643:18)
    at Promise._resolveCallback (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:459:14)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:529:17)
    at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._fulfillPromises (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:674:14)
    at Promise._settlePromises (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:700:18)
    at Promise._fulfill (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:643:18)
    at Promise._resolveCallback (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:437:57)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:529:17)
    at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:699:18)
    at Promise._fulfill (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:643:18)
    at Promise._resolveCallback (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:437:57)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:529:17)
    at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:699:18)
    at Promise._fulfill (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:643:18)
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/timers.js:26:46)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
[8/15/2019, 11:21:51 PM] [yamaha-zone-tv] Adding TV Control for Main
[8/15/2019, 11:21:51 PM] [yamaha-zone-tv] Adding TV Control for Zone2
Unhandled rejection Error: Cannot add a Service with the same UUID '000000D9-0000-1000-8000-0026BB765291' and subtype '15eb8e46-3ee2-4b1e-922a-366be0895315' as another Service in this Accessory.
    at PlatformAccessory.addService (/usr/local/lib/node_modules/homebridge/lib/platformAccessory.js:55:15)
    at YamahaZone.<anonymous> (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/index.js:547:24)
    at Array.forEach (<anonymous>)
    at YamahaZone.getServices (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/index.js:519:12)
    at YamahaAVRPlatform.<anonymous> (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/index.js:198:37)
    at tryCatcher (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:699:18)
    at Promise._fulfill (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:643:18)
    at Promise._resolveCallback (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:459:14)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:529:17)
    at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._fulfillPromises (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:674:14)
    at Promise._settlePromises (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:700:18)
    at Promise._fulfill (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:643:18)
    at Promise._resolveCallback (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:437:57)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:529:17)
    at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:699:18)
    at Promise._fulfill (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:643:18)
    at Promise._resolveCallback (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:437:57)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:529:17)
    at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:699:18)
    at Promise._fulfill (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/promise.js:643:18)
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/node_modules/bluebird/js/release/timers.js:26:46)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
[8/15/2019, 11:22:05 PM] [yamaha-zone-tv] Waited 10 seconds, stopping discovery.
[8/15/2019, 11:22:05 PM] [yamaha-zone-tv] Discovery finished, found 2 Yamaha AVR devices.
uncaughtException: Accessory MainY experienced an address collision.
[8/15/2019, 11:22:05 PM] Error: Accessory MainY experienced an address collision.
    at Server._handlePublishExternalAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:550:13)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:53:10)
    at API.emit (events.js:188:13)
    at API.publishExternalAccessories (/usr/local/lib/node_modules/homebridge/lib/api.js:113:8)
    at Timeout.timeoutFunction [as _onTimeout] (/usr/local/lib/node_modules/homebridge-yamaha-zone-tv/index.js:82:14)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
uncaughtException: Accessory MainY experienced an address collision.
[8/15/2019, 11:22:05 PM] MainY is running on port 53032.
[8/15/2019, 11:22:05 PM] Please add [MainY] manually in Home app. Setup Code: 513-23-537
[8/15/2019, 11:22:05 PM] Got SIGTERM, shutting down Homebridge...```

**Comment by NorthernMan54** [comment]
Great score

As I don’t have 2 receivers to test this with, going to need some help triaging and testing.

Looking at the log, thanks, it appears to be crashing due to duplicate names.  Are your devices and zones using unique names between both units?

**Comment by alexargo** [comment]
I actually thought it might be some kind of name collision and tried changing their names and still got the same issue. Nothing is called "MainY". On 'Basement' (Name of Receiver), I have 'Main' and 'Zone 2'. On 'Patio' (Name of Receiver), I changed the Zone names to "Covered Patio" and "Pool Area". The log from above is actually from after I changed the names. Is it possible there is some type of cached accessory info that saved the old names? (Used to be 'Main' and 'Zone 2' on both receivers).

**Comment by NorthernMan54** [comment]
Let me add more specific logging, give me a day or 2

**Comment by NorthernMan54** [comment]
If you can run the plugin in debug mode, it should log a lot more details around the issue

```
DEBUG=* homebridge
```

And share the output log file, it should give a clue into the name issue.

**Comment by alexargo** [comment]
Here's the log file... hopefully it makes sense to you. :) [homebridge-yamaha-zone-tv.log](https://github.com/NorthernMan54/homebridge-yamaha-zone-tv/files/3531852/homebridge-yamaha-zone-tv.log)

**Comment by NorthernMan54** [comment]
It did make perfect sense, please update and try again.  I don’t have 2 receivers to test with so am not sure if this worked or made things worse.  If it didn’t please include another DEBUG log.

Tks

**Comment by alexargo** [comment]
Here's the log with the new version. Of note, it doesn't seem to be picking up the new names I've given the zones, (just using Main and Zone2) even though I've changed them in the Yamaha app.
[homebridge-yamaha-zone-tv-2.log](https://github.com/NorthernMan54/homebridge-yamaha-zone-tv/files/3532813/homebridge-yamaha-zone-tv-2.log)

**Comment by NorthernMan54** [comment]
Sorry I got tied with work for a few weeks, but I made a small change and it should fix the issue.  Please update and try again.

**Comment by alexargo** [comment]
I don't know why you are apologizing. You aren't getting paid for this at all. Looks like it shows up as a HomeKit accessory and I can do stuff with it. I still get some error in my log about the inputs but no big deal.
